name: bakalari
version: 0.2.2
description: >-
        Wrapper for Czech school system Bakaláři. 
        Grants access to data that are not accessible
        by official app.
author: Petr Šťastný <petr.stastny01@gmail.com>
homepage: https://github.com/SoptikHa2/bakalari
environment:
        sdk: '>=2.1.0 <3.0.0'
dependencies:
        http: ^0.12.0
        xml: ^3.2.3
        intl: ^0.15.7
        pointycastle: ^1.0.0
        json_annotation: ^2.0.0

dev_dependencies:
        json_serializable: ^2.0.1
        build_runner: ^1.1.2