name: bakalari
version: 0.1.0
description: >-
        Package that allows reading data from Czech
        school system Bakaláři. This unofficial
        library grants access to data that may be
        locked in the official app - for example
        all grades weights.
author: Petr Šťastný <petr.stastny01@gmail.com>
environment:
        sdk: '>=2.1.0 <3.0.0'
dependencies:
        http: ^0.12.0
        xml: ^3.2.3
        intl: ^0.15.7
        pointycastle: ^1.0.0-rc4
