name: bakalari
version: 0.1.0
description: >-
        This package grants unofficial access to Bakaweb.
        Bakaweb is information system used in Czech schools.
        This package allows reading timetable, marks (including their's weights,
        even when not public by school) and subject average.
author: Petr Šťastný <petr.stastny01@gmail.com>
environment:
        sdk: '>=2.1.0 <3.0.0'
dependencies:
        http: ^0.12.0
        xml: ^3.2.3
        intl: ^0.15.7
        pointycastle: ^1.0.0-rc4
