name: bakalari
version: 0.1.0
description: >-
        This package grants unofficial access to Bakaweb.
        Bakaweb is information system used in Czech schools.
        This package allows reading timetable, marks (including their's weights,
        even when not public by school) and subject average.
author: Petr Šťastný <petr.stastny01@gmail.com>
environment:
        sdk: '>=2.1.0 <3.0.0'
dependencies:
        http: ^0.12.0
        xml: ^3.2.3
        intl: ^0.15.7
        # pointycastle. The newest version isn't available at pub, so it's manually downloaded
        # from pointcastle GitHub: https://github.com/PointyCastle/pointycastle/
        # The issue with pointycastle lacking latest version at pub repository is tracked here:
        # https://github.com/PointyCastle/pointycastle/issues/161
        # Here are pointycastle dependencies:
        # TODO: PointyCastle and dependencies